### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined  at validateString

### ISSUE THREAD

**Issue by yyhuaisha** [HerbertHe/electron-react-antd-antv-cli#9]
遇到这个问题，请问下载大家这个项目能跑通吗？

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[1]     at validateString (internal/validators.js:117:11)
[1]     at Object.join (path.js:1039:7)
[1]     at noopServiceWorkerMiddleware (/Users/admin/dev/message/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
[1]     at Layer.handle [as handle_request] (/Users/admin/dev/message/node_modules/express/lib/router/layer.js:95:5)
[1]     at trim_prefix (/Users/admin/dev/message/node_modules/express/lib/router/index.js:317:13)
[1]     at /Users/admin/dev/message/node_modules/express/lib/router/index.js:284:7
[1]     at Function.process_params (/Users/admin/dev/message/node_modules/express/lib/router/index.js:335:12)
[1]     at next (/Users/admin/dev/message/node_modules/express/lib/router/index.js:275:10)
[1]     at launchEditorMiddleware (/Users/admin/dev/message/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
[1]     at Layer.handle [as handle_request] (/Users/admin/dev/message/node_modules/express/lib/router/layer.js:95:5)

**Comment by HerbertHe** [comment]
可能是版本和配置项的问题，antd、react和electron在不断地更新，craco也不支持CRA4，没有经历维护这个旧的了，新开了个React SPA的封装，后期才会做electron适配emmm，那个会更纯粹一些
